FROM node:12.18.2-alpine3.12 as base
RUN apk update && apk upgrade && \
  apk add --no-cache bash git openssh tini
WORKDIR /var/www/
COPY . ./
RUN yarn install
RUN yarn build:no-lint
EXPOSE 3000
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["yarn", "start"]